# Generated by Django 4.0.2 on 2022-04-09 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created_at", models.DateTimeField(auto_now_add=True)),
                ("attachment", models.FileField(upload_to="%(app_name)s_files/")),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Classwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created_date", models.DateTimeField(auto_now_add=True)),
                ("_modified_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=5000)),
                ("modified", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("C_A", "ASSIGNMENT"),
                            ("C_Q", "QUESTION"),
                            ("C_T", "TEST"),
                            ("C_P", "POLL"),
                            ("C_D", "DEFAULT"),
                        ],
                        default="C_D",
                        max_length=3,
                    ),
                ),
                ("weightage", models.PositiveBigIntegerField(default=100)),
                ("attachments", models.BooleanField(default=False)),
                (
                    "_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created_date", models.DateTimeField(auto_now_add=True)),
                ("_modified_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=5000)),
                ("modified", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("R_N", "NOTES"),
                            ("R_B", "BOOKS"),
                            ("R_LP", "LECTURE_PLAN"),
                            ("R_M", "MEDIA"),
                            ("R_L", "LINKS"),
                            ("R_D", "DEFAULT"),
                        ],
                        max_length=4,
                    ),
                ),
                ("attachments", models.BooleanField(default=False)),
                (
                    "_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created_date", models.DateTimeField(auto_now_add=True)),
                ("_modified_date", models.DateTimeField(auto_now=True)),
                ("answer", models.CharField(max_length=5000)),
                ("grade", models.PositiveIntegerField(default=0)),
                ("remarks", models.CharField(max_length=5000)),
                ("modified", models.BooleanField(default=False)),
                ("graded", models.BooleanField(default=False)),
                ("attachments", models.BooleanField(default=False)),
                (
                    "_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionHasAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_submission",
                        to="classroom_contents.attachment",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_attachment",
                        to="classroom_contents.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceHasAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_resource",
                        to="classroom_contents.attachment",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_attachment",
                        to="classroom_contents.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassworkHasSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classwork_submission",
                        to="classroom_contents.classwork",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_classwork",
                        to="classroom_contents.submission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassworkHasAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_classwork",
                        to="classroom_contents.attachment",
                    ),
                ),
                (
                    "classwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classwork_attachment",
                        to="classroom_contents.classwork",
                    ),
                ),
            ],
        ),
    ]
