# Generated by Django 4.0.2 on 2022-05-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
