# Generated by Django 4.0.2 on 2022-05-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_contents', '0002_alter_attachment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classwork',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
