# Generated by Django 4.0.2 on 2022-05-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_contents', '0004_attachment_model_dump_attachment_tokenized_dump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='model_dump',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='tokenized_dump',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
