# Generated by Django 4.0.2 on 2022-04-09 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classroom_contents", "0001_initial"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created_date", models.DateTimeField(auto_now_add=True)),
                ("_modified_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=100)),
                ("classroom_code", models.CharField(max_length=32)),
                ("archive", models.BooleanField(default=False)),
                (
                    "_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_classroom",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classrooms",
            },
        ),
        migrations.CreateModel(
            name="ClassroomInviteOrRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created_date", models.DateTimeField(auto_now_add=True)),
                ("_modified_date", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("C", "Class Group"),
                            ("S", "Student"),
                            ("T", "Teacher"),
                        ],
                        max_length=1,
                    ),
                ),
                ("invited", models.BooleanField(default=True)),
                ("requested", models.BooleanField(default=False)),
                ("rejected", models.BooleanField(default=False)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_classroom_inviterequest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classgroup_inviterequest_classroom",
                        to="class_groups.classgroup",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_inviterequest",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_inviterequest_classroom",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_inviterequest_classroom",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classrooms Invites or Requests",
            },
        ),
        migrations.CreateModel(
            name="ClassroomHasTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_teacher",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_classroom",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classroom Teachers",
            },
        ),
        migrations.CreateModel(
            name="ClassroomHasStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_student",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_classroom",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classroom Students",
            },
        ),
        migrations.CreateModel(
            name="ClassroomHasSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_schedule",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_classroom",
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classroom Schedules",
            },
        ),
        migrations.CreateModel(
            name="ClassroomHasResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_resource",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_classroom",
                        to="classroom_contents.resource",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classroom Resources",
            },
        ),
        migrations.CreateModel(
            name="ClassroomHasClasswork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classroom_classwork",
                        to="classrooms.classroom",
                    ),
                ),
                (
                    "classwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classwork_classroom",
                        to="classroom_contents.classwork",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classroom Classworks",
            },
        ),
    ]
