# Generated by Django 4.0.2 on 2022-03-01 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("class_groups", "0001_initial"),
        ("classrooms", "0003_classroomhasschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinClassroomInviteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_created_date", models.DateTimeField(auto_now_add=True)),
                ("_modified_date", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("C", "Class Group"),
                            ("S", "Student"),
                            ("T", "Teacher"),
                        ],
                        max_length=1,
                    ),
                ),
                ("invite", models.BooleanField(default=True)),
                (
                    "_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_classroom_invite_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classgroup_classroom_invite_request",
                        to="class_groups.classgroup",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_classroom_invite_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_classroom_invite_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
