# Generated by Django 4.0.2 on 2022-04-09 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.class_groups.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_groups", "0001_initial"),
        ("classrooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classgrouphasclassroom",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classroom_classgroup",
                to="classrooms.classroom",
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="_created_by",
            field=models.ForeignKey(
                on_delete=models.SET(apps.class_groups.models.get_sentinel_user),
                related_name="created_classgroup",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
