# Generated by Django 4.0.2 on 2022-04-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("class_groups", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classgroupstudentinviteorrequest",
            old_name="created_by",
            new_name="_created_by",
        ),
        migrations.RenameField(
            model_name="classgroupstudentinviteorrequest",
            old_name="created_date",
            new_name="_created_date",
        ),
    ]
