# Generated by Django 4.0.2 on 2022-04-09 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveIntegerField(
                        choices=[
                            ("1", "SUNDAY"),
                            ("2", "MONDAY"),
                            ("3", "TUESDAY"),
                            ("4", "WEDNESDAY"),
                            ("5", "THURSDAY"),
                            ("6", "FRIDAY"),
                            ("7", "SATURDAY"),
                        ],
                        help_text="Pick from 1 to 7, 1 being Sunday and 7 being Saturday",
                    ),
                ),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("room", models.CharField(blank=True, max_length=20, null=True)),
                ("link", models.CharField(blank=True, max_length=1000, null=True)),
                ("note", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "_created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
